name: Check Links

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Check links
        run: make check_links
